services:
  kong-dbless:
    image: '${GW_IMAGE:-kong/kong-gateway:3.11.0.3}' # Kong Gateway image (default to latest version)
    container_name: kong-dbless-readonly
    read_only: true
    restart: unless-stopped
    networks:
      - kong-net
    volumes:
      - ./declarative:/kong/declarative/
      - ./tmp_volume:/tmp
      - ./prefix_volume:/var/run/kong
    #   - ./declarative:/kong/declarative
    #   - ./tmp_volume:/tmp:rw
    #   - ./prefix_volume:/var/run/kong:rw

    # tmpfs:
    #   - /tmp
    #   - /var/run/kong

    environment:
      KONG_PREFIX: /var/run/kong
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      
      # proxy listener (was 8000/8443 inside)
      KONG_PROXY_LISTEN: 0.0.0.0:8080, 0.0.0.0:8443 ssl

      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_GUI_API_URL: http://localhost:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
      - "8444:8444"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"

networks:
  kong-net:
    external: true